---
- name: Install system dependencies
  apt:
    name:
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
    update_cache: true
  become: true

- name: Remove bad version of libglib
  command: dpkg -r --force-all libglib2.0-0
  become: true

- name: Fix packages
  command: apt install -f -y
  become: true

- name: Install libglib dependent libraries
  apt:
    name:
      - libglib2.0-0
      - libglib2.0-dev
      - libcairo2-dev
      - libxt-dev
  become: true

- name: Add apt key by id from keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
  become: true

- name: Add repository
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/
  become: true

- name: Install R system package
  apt:
    name: r-base
    update_cache: true
  become: true

- name: Install R dependencies
  command: R -e 'install.packages("{{ item }}")'
  with_items:
    - 'XML'
    - 'plotly'
    - 'BiocManager'
  become: true

- name: Install bioconductor dependencies
  command: R -e 'BiocManager::install("{{ item }}", version = "3.8")'
  with_items:
    - "genefilter"
    - "GlobalAncova"
    - "impute"
    - "KEGGgraph"
    - "limma"
    - "pcaMethods"
    - "preprocessCore"
    - "Rgraphviz"
    - "siggenes"
    - "SSPA"
    - "sva"
  become: true

- name: Install metaboanalystr package
  command:
    R -e 'install.packages("devtools"); library(devtools); devtools::install_github("xia-lab/MetaboAnalystR")'
  become: true

- name: Install roxygen package
  command:
    R -e 'library(devtools); devtools::install_github("klutometis/roxygen")'
  become: true

- name: Copy metabulo R package to remote machine
  copy:
    src: ../../metabulo
    dest: "{{ ansible_env.HOME }}"

- name: Install metabulo R package
  command:
    R -e 'library(devtools); library(roxygen2); setwd("{{ ansible_env.HOME }}/metabulo"); document(); setwd("{{ ansible_env.HOME }}"); install("metabulo")'
  become: true

