version: 2
jobs:
  test_python:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: pip install -U 'tox>=3.7'
      - run: tox -p auto -o

  release:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          working_directory: ./web
          name: Install node dependencies
          command: yarn
      - run:
          working_directory: ./web
          name: Build web client
          command: |
            yarn build
            cp -R dist ../static/
      - run:
          name: Build python package
          command: |
            curl https://bootstrap.pypa.io/get-pip.py | python
            pip install tox
            tox -e release

  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          working_directory: ./devops
          name: Build and push Docker image
          command: |
            docker build -t metabulo/opencpu:latest .
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push metabulo/opencpu:latest

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test_python
      - release:
          requires:
            - test_python
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test_python
          filters:
            branches:
              only: master
