---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Include metaboanalystr tasks
      include_tasks: tasks/metaboanalystr.yml

    - name: Include opencpu tasks
      include_tasks: tasks/opencpu.yml

  post_tasks:
    - name: Enable opencpu
      systemd:
        name: "rstudio-server.service"
        daemon_reload: true
        enabled: true
        state: "started"
      become: true
