---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    venv: "{{ ansible_env.HOME }}/metabulo_venv"
  pre_tasks:
    - name: Install core system dependencies
      apt:
        name:
          - python3-dev
          - python3-venv
      become: true

  tasks:
    - name: Include metaboanalystr tasks
      include_tasks: tasks/metaboanalystr.yml

    - name: Include opencpu tasks
      include_tasks: tasks/opencpu.yml

    - name: Include metabulo tasks
      include_tasks: tasks/metabulo.yml

  post_tasks:
    - name: Enable opencpu
      systemd:
        name: "rstudio-server.service"
        daemon_reload: true
        enabled: true
        state: "started"
      become: true
