---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    venv: /home/gunicorn/venvs/metabulo
    sqlalchemy_database_uri: "sqlite:///${ansible_env.HOME}/db.sqlite3"
    upload_folder: "{{ ansible_env.HOME }}/files"
    opencpu_api_root: "http://localhost:8004/ocpu/library"
  pre_tasks:
    - name: Install core system dependencies
      apt:
        name:
          - python3-dev
          - python3-venv
      become: true

  tasks:
    - name: Include metaboanalystr tasks
      include_tasks: tasks/metaboanalystr.yml

    - name: Include opencpu tasks
      include_tasks: tasks/opencpu.yml

    - name: Include metabulo tasks
      include_tasks: tasks/metabulo.yml

  handlers:
    - name: Restart gunicorn
      systemd:
        name: "gunicorn.service"
        daemon_reload: true
        state: "reloaded"
      become: true
